title: Volume 13
description: > # this means to ignore newlines until "baseurl:"
  PMLR Volume 13
baseurl: "/v13"
url: "http://proceedings.mlr.press"
twitter_username: mlresearch
github_username:  mlresearch

# Build settings
markdown: kramdown
theme: minima
