---
booktitle: Proceedings of 2nd Asian Conference on Machine Learning
publisher: JMLR Workshop and Conference Proceedings
month: 0
volume: 13
year: '2010'
start: 2010-11-08
end: 2010-11-10
published: 2010-10-31
shortname: ACML
sections:
- name: preface
  title: Preface
- name: default
  title: Accepted Papers
layout: proceedings
series: Proceedings of Machine Learning Research
id: SugiyamaACML2010
abstract: ''
editor:
- given: Masashi
  family: Sugiyama
- given: Qiang
  family: Yang
title: Proceedings of Machine Learning Research
description: |
  Proceedings of 2nd Asian Conference on Machine Learning
    Held in Tokyo, Japan on 8-10 November 2010

  Published as Volume 13 by the Proceedings of Machine Learning Research on 31 October 2010.

  Volume Edited by:
    Masashi Sugiyama
    Qiang Yang

  Series Editors:
    Neil D. Lawrence
url: http://proceedings.mlr.press
baseurl: "/v13"
twitter_username: mlresearch
github_username: mlresearch
markdown: kramdown
permalink: "/:title.html"
github:
  edit: true
  repository: v13
email: ''
conference:
  name: Proceedings of 2nd Asian Conference on Machine Learning
  url: 
  location: Tokyo, Japan
  dates:
  - 2010-11-08
  - 2010-11-09
  - 2010-11-10
analytics:
  google:
    tracking_id: UA-92432422-1
# Site settings
# Auto generated from v13.bib
